fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    apt:    git://github.com/puppetlabs/puppetlabs-apt.git
    git:    git://github.com/puppetlabs/puppetlabs-git.git
    ntp:    git://github.com/puppetlabs/puppetlabs-ntp.git
    apache: git://github.com/puppetlabs/puppetlabs-apache.git
    docker: git://github.com/puppetlabs/puppetlabs-docker_platform.git
  symlinks:
    "g10b": "#{source_dir}"