---
puppet::host : 'puppet'
puppet::port : 8140

gitlab::host : 'repositories'
gitlab::port : 80

jenkins::host : 'karajan'
jenkins::port : 8080

mesos::host        : 'karajan'
mesos::master_port : 5050
mesos::log_dir     : '/var/log/mesos'
mesos::conf_dir    : '/etc/mesos'
mesos::owner       : 'mesos'
mesos::group       : 'mesos'

rundeck::host  : 'karajan'
rundeck::port  : 4440
rundeck::user  : 'rundeck'
rundeck::group : 'rundeck'

pass:
  - path: /puppet
    url: http://puppet.oloc:8140
  - path: /rundeck
    url: http://karajan.oloc:4440
  - path: /gitlab
    url: http://repositories.oloc:80/gitlab
  - path: /jenkins
    url: http://karajan.oloc:8080/jenkins
  - path: /mesos
    url: http://karajan.oloc:5050/
